### ISSUE TITLE
CHECKOUT_URL Not Calling

### ISSUE THREAD

**Issue by farmanafridi786** [apps-payfast/example-code#2]
Hello!
i am trying to integrate PayFast to one of my client website and after successful transaction i found that PayFast did't call my server CHECKOUT_URL which i send to PayFast server in checkout redirect. 
It's should ping my backend server so that i confirm the payment

**Comment by apps-official-internal** [comment]
For redirection,  SUCCESS_URL and FAILURE_URL will be used. CHECKOUT_URL will be used for payment notification web hook which needs to be enabled upon Merchant request.

**Comment by farmanafridi786** [comment]
where to request  for webhook? there is no such a feature in merchant portal

**Comment by apps-official-internal** [comment]
> where to request for webhook? there is no such a feature in merchant portal



> where to request for webhook? there is no such a feature in merchant portal

Kindly send request via your contact person/sales executive or the provided official email address. For now web hook can not be enabled via Merchant Portal.

**Comment by farmanafridi786** [comment]
> > where to request for webhook? there is no such a feature in merchant portal
> 
> > where to request for webhook? there is no such a feature in merchant portal
> 
> Kindly send request via your contact person/sales executive or the provided official email address. For now web hook can not be enabled via Merchant Portal.

but you guys should have such a feature in merchant portal so that we can resend the notification if we needed and this type of feature had already in every payment getaway out there

**Comment by apps-official-internal** [comment]
Yes, this is in our roadmap and will be available very soon.
